name: CI Basic
on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: List container
        run: docker-compose ps
      - name: uname
        run: uname -a
      - name: ping localhost
        run: ping localhost
      - name: ping 127.0.0.1
        run: ping 127.0.0.1
      - name: ping 127.0.0.1
        run: tracert 127.0.0.1
      - name: cat release
        run: cat /etc/lsb-release
      - name: Netsat
        run: netstat -plnt
      - name: wget 127
        uses: wei/wget@v1
        with:
          args: -O home.html http://127.0.0.1:8080
      - name: wget localhost
        uses: wei/wget@v1
        with:
          args: -O home.html http://localhost:8080


