name: CI Basic
on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: docker-compose -f docker-compose.yml up -d
      - name: logs
        run: docker logs dvpwa_ip_demo_postgres_1
      - name: whoami
        run: whoami
      - name: uname
        run: uname -a
      - name: ping localhost
        run: ping -c 4 localhost
      - name: ping 127.0.0.1
        run: ping -c 4 127.0.0.1
      - name: cat release
        run: cat /etc/lsb-release
      - name: Netstat
        run: netstat -plnt
#      - name: wget 127
#        uses: wei/wget@v1
#        with:
#          args: -O home.html http://127.0.0.1:8080
#      - name: wget localhost
#        uses: wei/wget@v1
#        with:
#          args: -O home.html http://localhost:8080
#      - name: telnet
#        run: telnet 127.0.0.1 8080
      - name: nc
        run: nc -vz 127.0.0.1 8080
#      - name: Set docker container id
#        run:  echo "DOCKER_CONTAINER_ID=$(docker ps -a | grep "dvpwa_ip_demo_sqli" | cut -d " " -f1)" >> $GITHUB_ENV
#      - name: Set webapp IP
#        run: echo "DOCKER_WEB_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $DOCKER_CONTAINER_ID )" >> $GITHUB_ENV
      - name: ifconfig
        run: ifconfig
#      - name: docker ps
#        run: docker ps -a
#      - name: Sleep for 90 seconds
#        run: sleep 90s
#        shell: bash
#      - name: docker ps
#        run: docker ps -a
      - name: ufw
        run: ufw status
      - name: curl
        run: curl -v http://localhost:8080
#      - name: wget ip
#        uses: wei/wget@v1
#        with:
#          args: http://localhost:8080