name: CI Basic
on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: List container
        run: docker-compose ps
      - name: uname
        run: uname -a
      - name: ping localhost
        run: ping -n 4 localhost
      - name: ping 127.0.0.1
        run: ping -n 4 127.0.0.1
      - name: cat release
        run: cat /etc/lsb-release
      - name: Netstat
        run: netstat -plnt
#      - name: wget 127
#        uses: wei/wget@v1
#        with:
#          args: -O home.html http://127.0.0.1:8080
#      - name: wget localhost
#        uses: wei/wget@v1
#        with:
#          args: -O home.html http://localhost:8080
      - name: Netstat
        run: netstat -plnt
      - name: Set docker container id
        run: docker ps -a | grep "dvpwa_ip_demo_sqli" | cut -d " " -f1 >> $DOCKER_CONTAINER_ID
      - name: Set webapp IP
        run: docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $DOCKER_CONTAINER_ID >> $DOCKER_WEB_IP
      - name: Set webapp IP
        run: docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $DOCKER_CONTAINER_ID >> $DOCKER_WEB_IP
      - name: wget localhost
        uses: wei/wget@v1
        with:
          args: -O home.html http://$DOCKER_WEB_IP:8080