name: CI Basic
on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: List container
        run: docker-compose ps
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O home.html http://localhost:8080

